spring:
  datasource:
    url: jdbc:mysql://${db.host:localhost}:3306/${db.scheme:shopping}
    username: ${db.username:root}
    password: ${db.password:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: Asia/Seoul
        show_sql: true
    show-sql: true
  data:
    redis:
      host: ${redis.host:localhost}
      port: ${redis.port:6379}
      ssl:
        enabled: ${redis.ssl.enabled:false}
      timeout: 5000
  kakao:
    auth:
      redirect: http://localhost:8080/auth/login/kakao
      client: ${KAKAO_AUTH_CLIENT}
      secret: ${KAKAO_AUTH_SECRET}
      admin-key: ${KAKAO_AUTH_ADMIN_KEY}
  cloud:
    aws:
      s3:
        bucket: ${AWS_S3_BUCKET:jnsj-file-upload-bucket}
      credentials:
        access-key: ${AWS_S3_ACCESS_KEY}
        secret-key: ${AWS_S3_SECRET_KEY}
      region:
        static: ap-northeast-2
      stack:
        auto: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      faq-vector-store-id: ${OPENAI_FAQ_VECTOR_STORE_ID}
      chat:
        options:
          model: gpt-3.5-turbo


jwt:
  secret: ${kt.jwt.secret:1234567890123456789012345678901234}
  access-token-expiration: ${kt.jwt.access-token-expiration:300000}
  refresh-token-expiration: ${kt.jwt.refresh-token-expiration:43200000}


slack:
  bot-token: ${slack.token:1234}
  log-channel: ${slack.channel:1234}

delivery:
  policy:
    max-address-count: 10

aws:
  ses:
    access-key: ${AWS_SES_ACCESS_KEY}
    secret-key: ${AWS_SES_SECRET_KEY}
    send-mail-from: whtndus0809@gmail.com
  region: ap-northeast-2
